version: '{build}'
os: Visual Studio 2015
configuration: Release
platform: Any CPU

build_script:
 - ps: .\build.ps1 -Target Default -Configuration $Env:Configuration
  
artifacts:
 - path: output
 - path: output\obfuscated\*.exe
 - path: output\*.nupkg
